/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pt.paper;

/**
 *
 * @author patrick_huy
 */
public class data {
    public static String[] testData = {
        "make Bread Roll Demonstration", //0
        "Ingredient Roll", //1
        "Recipe Dough Bread", //Sourdough									//2
        "Recipe Dough Ingredient", //3
        "Homemade Bread Recipe", //4
        "make Homemade Bread", //5
        "Human interface computer", //6
        "survey user computer system response time", //7	
        "EPS user interface system", //8
        "System human system EPS", //9
        "user response time",//10	
        "trees", //11
        "graph trees", //12
        "Graph minors trees", //13
        "Graph minors survey", //14
        "Medicine ingredient make Drowsiness", //15
        "Drugs Medicine treat Drowsiness", //16
        "treat drugs", //17
        "Rock Roll Music", //18
        "Drum Roll Demonstration", //19
        "Drum Composition", //20
        "Rock Music", //21
        "Music Composition", //22
        "Effect Music Human Response", //23
        "Rock Music System", //24
        "effect music",//25
        "make bread",//Q1
        "treat Drowsiness", //q2
        "effect rock music" //q3
    };
    
    
/**
 * TODO: add job search data
 */
    public  static String[] inputJobSearch = {
        "lập_trình_viên | sinh_viên | thời_gian | gắn_kết | lâu_dài | cộng_tác_viên | năng_lực | nhu_cầu",
        "kế_toán_trưởng | kế_toán | bồi_dưỡng | kế_toán_trưởng | hành_chính | sự_nghiệp | thông_tư | tài_chính | tiêu_chuẩn | kế_toán_trưởng | kế_toán_trưởng | kế_toán_trưởng | thì_phải | bồi_dưỡng | kế_toán_trưởng | nhu_cầu | ngày_càng | đào_tạo | kế_toán | trường_bồi_dưỡng_cán_bộ_tài_chính | kế_toán_trưởng | doanh_nghiệp | đào_tạo | kế_toán_trưởng | hành_chính | sự_nghiệp | đối_tượng | tốt_nghiệp | chuyên_ngành | tài_chính | tốt_nghiệp | đại_học | kế_toán | thực_tế | trở_lên | trung_học | cao_đẳng | kế_toán | thực_tế | trở_lên | đào_tạo | kế_toán_trưởng | doanh_nghiệp | kế_toán_trưởng | chuyên_đề | tiến_sĩ | giảng_viên | kinh_nghiệm | tài_chính | học_phí | kế_toán_trưởng | doanh_nghiệp | tài_liệu | chứng_chỉ | kế_toán_trưởng | tài_liệu | học_viên | đăng_ký | khai_giảng | đặc_biệt | bồi_dưỡng | kế_toán_trưởng | khóa_excel | ghi_chú | đăng_ký | xác_nhận | đào_tạo | kế_toán_trưởng | học_viên | chứng_chỉ | kế_toán_trưởng | kế_toán_trưởng | doanh_nghiệp | trưởngdoanh | doanh_nghiệp | kế_toán_trưởng | hành_chính | sự_nghiệp | kế_toán_trưởng | hành_chính | sự_nghiệp | lớp_học | kế_toán_trưởng | hành_chính | sự_nghiệp | địa_chỉ | doanh_nghiệp | trung_tâm_đào_tạo_kế_toán_vaft | tòa_nhà | địa_điểm_tại | trương_định | website",
        "kế_toán | công_việc | dữ_liệu | báo_cáo | giao_dịch | ngân_hàng | ưu_tiên | triệutháng | thu_mua | thực_hiện | yêu_cầu | báo_cáo | ưu_tiên | triệutháng | e_commerce | chỉnh_sửa | hình_ảnh | cập_nhật | nội_dung | sản_phẩm | công_việc | yêu_cầu | ưu_tiên | tiếng_anh | làm_việc | nhà_hàng | phục_vụ | nhà_hàng | biết_tiếng_anh | giao_tiếp | phục_vụ | nhà_hàng | phân_công | nhà_hàng | kinh_nghiệm | triệutháng | làm_việc | nhân_sự",
        "tuyển_dụng | nhân_viên | kinh_doanh | tuyển_dụng | nhân_viên | kinh_doanh | mở_rộng | hoạt_động | hơn_nữa | nhu_cầu | quảng_cáo | cũng_như | giới_thiệu | doanh_nghiệp | chúng_tôi | số_lượng | địa_điểm | nhân_viên | kinh_doanh | khai_thác | sản_phẩm | công_ty | cung_cấp | khách_hàng | đàm_phán | thuyết_phục | khách_hàng | sản_xuất | doanh_nghiệp | sản_phẩm | truyền_hình | phim_tài_liệu | quay_phim | dịch_vụ | hội_nghị | hội_thảo | khánh_thành | khai_trương | đám_cưới | đám_hỏi | liên_hệ | chỉ_đạo | công_ty | yêu_cầu | trung_cấp | trở_lên | ứng_viên | truyền_thông | báo_chí | kinh_nghiệm | giao_tiếp | công_việc | kinh_doanh | chăm_sóc | khách_hàng | tin_học | văn_phòng | tổ_chức | công_việc | khoa_học | ưu_tiên | công_việc | lâu_dài | hợp_đồng | lao_động | lao_động | đãi_ngộ | xứng_đáng | phù_hợp | định_kỳ | hoạt_động | kinh_doanh | phúc_lợi | liên_hoan | nghỉ_mát | hoạt_động | văn_thể | lý_lịch | công_tác | chính_thức | nhân_dân | hộ_chiếu | bản_sao | công_chứng | khai_sinh | sổ_hộ_khẩu | bản_sao | công_chứng | chứng_chỉ | dự_tuyển | thư_điện_tử | trực_tiếp | ứng_viên | tiếng_việt",
        "outsourcing | pythonjavaphp | kỹ_thuật | kỹ_năng | giải_trí | thể_thao | sức_khỏe | sức_khỏe | cao_cấp",
        "xây_dựng | hệ_thống | giao_nhận | chuyên_nghiệp | thường_xuyên | chào_đón | du_lịch",
        "chiêu_mộ | full_stack_dev | thiết_bị | nhân_viên | xuất_sắc | miễn_phí | bảo_việt",
        "các_java_full_stack_dev | software | văn_phòng | sài_gòn | teambuilding | thể_thao | sức_khỏe",
        "các_senior | iosjava | net_mvc | sài_gòn | công_ty | làm_việc | linh_hoạt | macbook_pro | quốc_tế | hàng_loạt | trong_ngoài",
        "rails_dev | mới_đây | training | hấp_dẫn | lên_tay | giải_trí | miễn_phí | hoạt_động | thể_thao",
        "tuyển_dụng | nhân_viên | kinh_doanh | lốp_xe_máy | công_trình | số_lượng | mô_tả_công_việc | khách_hàng | kế_hoạch | kinh_doanh | yêu_cầu | giới_thiệu | sản_phẩm | kinh_doanh | đánh_giá | diễn_biến | thị_trường | yêu_cầu | cao_đẳng | trở_lên | giao_tiếp | đàm_phán | thuyết_phục | trung_thực | khát_khao | phát_triển | lâu_dài | thành_thạo | internet | lợi_thế | quyền_lợi | phần_trăm | doanh_thu | làm_việc | công_việc | thông_tin | hồ_sơ_gồm | lý_lịch | chứng_chỉ | giấy_tờ | đối_chiếu | bản_chính",
        "công_ty | bất_động_sản | chăm_sóc | khách_hàng | hiện_tại | trao_đổi | kinh_nghiệm | bất_động_sản | ưa_nhìn | trở_lên | kinh_nghiệm | làm_việc | điều_phối | lưu_loát | ứng_tuyển",
        "công_ty | công_ty | kế_toán | kiểm_soát | yêu_cầu | ít_nhất | thu_nhập | địa_điểm | làm_việc | kế_toán | kiểm_soát",
        "cần_tuyển_gấp | nhân_viên | kinh_doanh | thiết_bị | nhập_khẩu | lắp_đặt | hệ_thống | chủ_nhật | nhà_nước | yêu_cầu | tốt_nghiệp | trung_cấp | trở_lên | kinh_tế | kỹ_thuật | ưu_tiên | hợp_đồng | địa_điểm | làm_việc | biệt_thự | đường_nguyễn_văn_linh | long_biên | hồ_chí_minh | thành_phố_hồ_chí_minh | nhu_cầu | trannham@gmailcom | liên_hệ | hotline | miss_nhâm | điện_thoại | trao_đổi | trực_tiếp | công_việc | trân_trọng",
        "tuyển_nv_lắp_ráp | lao_động_phổ_thông | trung_tâm_nội_thất_phố_xinh | nhân_viên | lắp_ráp | địa_điểm | làm_việc | lê_văn_lương_kéo | vận_chuyển | lắp_đặt | nội_thất | công_việc | làm_việc | liên_hệ | thuynsphoxinh@gmailcom",
        "tuyển_dụng | tuyển_dụng | nhân_viên | chăm_sóc_khách_hàng | công_việc | parttime | nhiệt_tình | đào_tạo | kinh_nghiệm | liên_hệ | tuyethrdaiichi@gmailcom | thông_tin",
        "thông_báo_tuyển_dụng | nhân_sự | kinh_doanh | chăm_sóc | khách_hàng | thời_gian | làm_việc | địa_điểm | nguyễn_xí | bình_thạnh | quyền_lợi | kỹ_năng | chuyên_môn | năng_lực | bản_thân | thông_tin | liên_hệ | bmt@gmailcom | thắc_mắc | liên_hệ | phản_hồi",
        "nhu_cầu | tuyển_dụng | kế_toán_tổng_hợp | làm_việc | cửa_nam | chủ_nhật | lao_động | tối_thiểu | xây_dựng | quản_lý | thi_công | hatranganviet@gmailcom",
        "nhân_viên | phụ_cấp | nhân_viên | nội_dung_công_việc | nhan_hàng_ở_sân_bay_tân_sơn_nhất | sau_đó_đem_giao_ở_các_nơi | thông_tin_liên_hệ | gặp_nhiền", 
        "công_ty | nhân_viên | kế_toán | số_lượng | yêu_cầu | trở_lên | tin_học | văn_phòng | học_hỏi | quyền_lợi | phụ_cấp | công_ty | địa_chỉ | làm_việc | đồng_văn | liên_hệ",
        "nhân_viên | telesale | làm_việc | giờ_hành_chính | nghỉ_chủ_nhật | chiều_thứ | địa_điểm | làm_việc | yêu_cầu | trung_cấp | trở_lên | nhiệt_tình | công_việc | kinh_doanh | quyền_lợi_hấp_dẫn | doanh_thu | đào_tạo | kỹ_năng_chuyên_môn | hiệu_quả | kinh_doanh | liên_hệ",
        "hợp_đồng | tuyển_dụng | công_ty | hoạt_động | kinh_nghiệm | cao_đẳng | thu_nhập | ổn_định | hợp_đồng | nhân_sự | bình_quân | _trtháng | hotline",
        "công_ty | nhân_viên | chăm_sóc | khách_hàng | số_lượng | trung_cấp | trở_lên | ưu_tiên | trung_cấp | công_việc | chăm_sóc | khách_hàng | làm_việc | giờ_hành_chính | nhiệt_tình | hợp_đồng | hotline | địa_chỉ | hiệp_tân | hòa_thành | tây_ninh | đối_diện",
        "kỹ_thuật_viên_qui_trình | processtechnician | công_việc | kiểm_tra | bảo_trì | chăm_sóc | bảo_dưỡng | máy_móc | định_kỳ | báo_cáo | sản_phẩm | bộ_phận | liên_quan | khắc_phục | phương_án | cải_tiến | hiệu_quả | sử_dụng | thiết_bị | máy_móc | thiết_bị | sản_xuất | cải_tiến | sản_xuất | công_việc | trung_cấp | điện_tử | liên_quan | bảo_trì | vận_hành | hiểu_biết | cải_tiến | sản_xuất | doan@friwocom | tnhh_friwo_vn | tuyển_dụng",
        "công_ty | lĩnh_vực | mỹ_phẩm | nhân_viên | kinh_doanh | thị_trường | số_lượng | giới_tính | chuyên_ngành | quản_trị | kinh_doanh | chuyên_ngành | kinh_nghiệm | chuyên_viên | nghiên_cứu | thị_trường | số_lượng | giới_tính | chuyên_ngành | quản_trị | kinh_doanh | chuyên_ngành | kinh_nghiệm | nghiên_cứu | thị_trường | ưu_tiên | phiên_dịch | tiếng_anh | kinh_doanh | số_lượng | giới_tính | chuyên_ngành | tiếng_anh | chuyên_ngành | kinh_nghiệm | ít_nhất | làm_việc | nhân_viên | marketing | số_lượng | giới_tính | chuyên_ngành | marketing | liên_quan | kinh_nghiệm | trở_lên | marketing | địa_chỉ | làm_việc | công_ty | hàn_quốc | sản_xuất | sản_xuất | đầu_tiên | trực_tiếp | sản_xuất | thực_phẩm | sản_xuất | mỹ_phẩm | nắm_bắt | sử_dụng | việt_nam | công_ty | nhu_cầu | sản_xuất | website | industrial | province | hwaseong | kyunggi_do | liên_lạc | nhân_sự | địa_chỉ",
        "công_ty | kinh_doanh | yêu_cầu | dịch_vụ | ứng_viên | tìm_kiếm | công_việc | thuận_buồm_xuôi_gió",
        "làm_việc | chuyên_nghiệp | giao_tiếp | tập_đoàn_hoa_sao | tập_đoàn_hoa_sao_tuyển_dụng | nhân_viên_chăm_sóc_khách_hàng | địa_điểm | làm_việc | thời_gian | làm_việc | đào_tạo | tiếp_nhận | tổng_đài | lắp_đặt | kỹ_thuật | tiếp_nhận | nội_dung | cuộc_gọi | liên_quan | truyền_hình_cáp | trung_ương | lưu_trữ | cập_nhật | cần_thiết | quản_lý | thông_tin | khảo_sát | thông_tin | khách_hàng | nhân_viên_tư_vấn_tài_chính | hoa_hồng | thu_nhập | làm_việc | khách_hàng | tiềm_năng | dịch_vụ | tài_chính | sản_phẩm | tín_dụng | khách_hàng | thủ_tục | hướng_dẫn | nghiệp_vụ | pháp_lý | hợp_pháp | khảo_sát | thẩm_định | tài_chính | chứng_từ | thông_báo | kết_quả | thẩm_định | tình_hình | hoạt_động | trực_tiếp | phát_hiện | nghi_ngờ | gian_lận | trực_tiếp | phòng_ban | liên_quan | mô_tả_công_việc | làm_việc | làm_việc | cuộc_gọi | khách_hàng | giải_đáp | thắc_mắc | hướng_dẫn | lựa_chọn | sản_phẩm | xác_nhận | bàn_giao | khiếu_nại | đối_với | yêu_cầu_công_việc | trở_lên | nhẹ_nhàng | địa_phương | kỹ_năng | linh_hoạt | tình_huống | chăm_chỉ | chịu_khó | ngoan_ngoãn | cẩn_thận | làm_việc | thực_tập | phân_biệt | phù_hợp | yêu_thích | phỏng_vấn_số | dám_đương_đầu",
        "thông_báo | tuyển_dụng | kế_toán | tổng_hợp | số_lượng | yêu_cầu | đại_học | chuyên_ngành | kế_toán | tài_chính | kinh_nghiệm | xây_dựng | vi_tính | văn_phòng | tinh_thần | học_hỏi | phỏng_vấn | làm_việc | giờ_hành_chính | thỏa_thuận | congdoannuce@gmailcom | địa_chỉ | văn_phòng | công_ty",
        "v_english | công_việc | tìm_kiếm | khách_hàng | sinh_viên | thu_thập | thông_tin | khách_hàng | khách_hàng | khách_hàng | bộ_phận | ghi_danh | yêu_cầu | nhiệt_tình | học_hỏi | quyền_lợi | thời_gian | làm_việc | linh_động | đào_tạo | đào_tạo | đào_tạo | lãnh_đạo | kinh_doanh | hoa_hồng | trao_đổi | phỏng_vấn | bản_sao | hộ_khẩu | bản_sao | liên_quan | tóm_tắt | giới_thiệu | liên_hệ | địa_chỉ | điện_thoại",
        "công_ty | tu_nghiệp_sinh | số_lượng | quản_lý | tu_nghiệp_sinh | nhật_bản | kiểm_tra | thăm_hỏi | tu_nghiệp_sinh | hoàn_thành | giấy_tờ | giao_tiếp | báo_cáo | yêu_cầu | cao_đẳng | đại_học | trở_lên | tương_đương | thực_tập_sinh | quyền_lợi | trợ_cấp | internet | năng_lực | làm_việc | địa_điểm | làm_việc | fukouka | nhật_bản | cách_thức | ứng_tuyển | ứng_tuyển | bắt_buộc | nhansu@minanotamevn | ứng_tuyển | tu_nghiệp_sinh | thắc_mắc | công_ty | giai_đoạn | mở_rộng | liên_quan | chào_đón | tiếng_nhật | công_ty | tuyển_dụng | trực_tiếp | trung_gian",
        "số_lượng | mức_lương | usdtháng | địa_điểm_làm_việc | mô_tả_công_việc | định_kỳ | nhật_bản | thị_trường | chăm_sóc | khách_hàng | nghiệp_đoàn | lao_động | hợp_tác | công_tác | chăm_sóc | khách_hàng | đối_tác | phát_sinh | đối_tác | yêu_cầu | yêu_cầu | trung_cấp | cao_đẳng | trở_lên | tương_đương | ứng_viên | kinh_nghiệm | thực_tế | nhân_sự | kinh_doanh | chăm_sóc | khách_hàng | đối_tác | nhật_bản | quyền_lợi | hấp_dẫn | lương_usdtháng | ngoàiracòncócácchếđộthưởngkhác | căng_tin | đào_tạo | đào_tạo | trực_tiếp | làm_việc | thân_thiện | thăng_tiến | công_việc | đào_tạo | thường_xuyên | năng_lực | làm_việc | nướcsau | thángthửviệc | địa_điểm_làm_việc | liên_hệ | bắt_buộc | tiếng_việt | nhansu@minanotamevn | tiêu_đề | nhânviênpháttriểnthịtrường | liên_hệ | công_ty | giai_đoạn | mở_rộng | liên_quan | chào_đón | tiếng_nhật | công_ty | tuyển_dụng | trực_tiếp | trung_gian",
        "tuyển_dụng | công_ty | yêu_cầu | sức_khỏe | số_lượng | địa_điểm | làm_việc | đồng_nai | phúc_lợi | nghỉ_phép | sức_khỏe | bằng_cấp | liên_hệ | nhân_viên | phát_triển | thị_trường | chức_vụ | nhân_viên | ngành_nghề | ngành_nghề | hình_thức | làm_việc | địa_điểm | làm_việc | bình_dương | đồng_nai | học_việc | công_việc | tìm_kiếm | khách_hàng | làm_việc | quyền_lợi | quyền_lợi | qui_định | kinh_nghiệm | yêu_cầu | bằng_cấp | yêu_cầu | giới_tính | yêu_cầu | yêu_cầu | siêng_năng | trung_thực | họat_bát | tốt_nghiệp | lý_lịch | địa_phương | nhân_dân | hộ_khẩu | thường_trú | công_chứng | văn_bằng | chứng_chỉ | công_ty | hình_thức | trực_tiếp | liên_hệ",
        "v_english | công_việc | tìm_kiếm | khách_hàng | sinh_viên | thu_thập | thông_tin | khách_hàng | khách_hàng | khách_hàng | bộ_phận | ghi_danh | yêu_cầu | nhiệt_tình | học_hỏi | quyền_lợi | thời_gian | làm_việc | linh_động | đào_tạo | đào_tạo | đào_tạo | lãnh_đạo | kinh_doanh | hoa_hồng | trao_đổi | phỏng_vấn | bản_sao | hộ_khẩu | bản_sao | liên_quan | tóm_tắt | giới_thiệu | liên_hệ | địa_chỉ | nguyễn_hữu_thọ | điện_thoại",
        "công_ty | nhân_viên | giám_đốc | kiểm_tra | bảo_dưỡng | bảo_dưỡng | quản_lý | yêu_cầu | trung_cấp | quản_lý | quyền_lợi | thỏa_thuận | tương_xứng | công_việc | trình_độ | hiện_hành | công_ty | yêu_cầu | lý_lịch | chứng_minh | nhân_dân | bằng_cấp | liên_hệ | công_ty_tnhh | cộng_đồng | địa_chỉ | liên_hệ | ms_hương | viendinhduong",
        "tuyển_dụng | trình_độ | cao_đẳng | trở_lên | giới_tính | kinh_nghiệm | đào_tạo | kĩ_năng | số_lượng | mô_tả_công_việc | khách_hàng | mở_rộng | mạng_lưới | kinh_doanh | định_vị | nhu_cầu | dịch_vụ | thiết_bị | kế_hoạch | mở_rộng | kinh_doanh | yêu_cầu | quyền_lợi_được_hưởng | thăng_tiến | làm_việc | chuyên_nghiệp | ổn_định | lâu_dài | điện_thoại | yêu_cầu_khác | cao_đẳng | trở_lên | cẩn_thận | giao_tiếp | công_việc | lợi_thế | trực_tiếp | thông_tin_liên_hệ | đường_hồ_rùa | phố_nguyễn_lân | phương_liệt | thanh_xuân | hạn_nộp_hồ_sơ",
        "công_ty | công_ty | phần_mềm | kế_toán | nhân_viên | chăm_sóc | khách_hàng | công_việc | điện_thoại | kế_toán | triển_khai | cài_đặt | hợp_đồng | kinh_doanh | triển_khai | nhẹ_nhàng | dễ_tính | công_việc | du_lịch | địa_phương",
        "trung_tâm | dịch_vụ | chăm_sóc | thu_ngân | yêu_cầu | thành_thạo | tiếng_hàn | kinh_nghiệm | quyền_lợi | phỏng_vấn | địa_điểm | làm_việc | spa_dan | phố_hoàng_ngân | nhu_cầu | ms_ngoc",
        "tuyển_dụng_nhân_sự | vị_trí_trợ_lý_tuyển_dụng | yêu_cầu | bằng_cấp | tốt_nghiệp | cao_đẳng | trở_lên | số_lượng | thời_gian | yêu_cầu | mô_tả_công_việc | quản_lý | hướng_dẫn | ứng_viên | thủ_tục | tuyển_dụng | ứng_viên | kèm_cặp | ban_đầu | nhân_viên | quyền_lợi_được_hưởng | năng_động | chuyên_nghiệp | hấp_dẫn | thăng_tiến | công_bằng | nước_ngoài | hoàn_thành | đào_tạo | nghiệp_vụ | thường_xuyên | yêu_cầu_khác | nhiệt_tình | kinh_nghiệm | kế_toán | tài_chính | vị_trí_nhân_viên_kinh_doanh | mô_tả_công_việc | khách_hàng | công_việc | quyền_lợi_đc_hưởng | chuyên_nghiệp | năng_động | đào_tạo | chuyên_môn | nhân_viên | chuyên_nghiệp | khả_năng | thăng_tiến | đào_tạo | thường_xuyên | phát_triển | bản_thân | xứng_đáng | yêu_cầu_công_việc | kinh_nghiệm | địa_chỉ_chi_tiết_nơi_làm_việc | thông_tin_liên_hệ",
        "phòng_trọ_việt | công_việc | tìm_kiếm | khách_hàng | khách_hàng | công_việc | yêu_cầu | kinh_nghiệm | chúng_tôi | nhiệt_tình | học_hỏi | quyền_lợi | thu_nhập | công_việc | thời_gian | làm_việc | linh_động | đào_tạo | đào_tạo | quản_lý | phỏng_vấn | bản_sao | hộ_khẩu | bản_sao | liên_quan | tóm_tắt | giới_thiệu | liên_hệ | địa_chỉ | nguyễn_hữu_thọ | điện_thoại",
        "tuyển_dụng | hành_chính | văn_phòng | số_lượng | giới_tính | mô_tả_công_việc | thủ_tục | pháp_lý | công_việc | sử_dụng | kinh_nghiệm | đào_tạo | kĩ_năng | số_lượng | trình_độ | cao_đẳng | trở_lên | giới_tính | kinh_nghiệm | đào_tạo | kĩ_năng | số_lượng | mô_tả_công_việc | khách_hàng | mở_rộng | mạng_lưới | kinh_doanh | định_vị | nhu_cầu | dịch_vụ | thiết_bị | kế_hoạch | mở_rộng | kinh_doanh | yêu_cầu | quyền_lợi_được_hưởng | thăng_tiến | làm_việc | chuyên_nghiệp | ổn_định | lâu_dài | điện_thoại | yêu_cầu_khác | cao_đẳng | trở_lên | cẩn_thận | giao_tiếp | công_việc | lợi_thế | trực_tiếp | thông_tin_liên_hệ | đường_hồ_rùa | phố_nguyễn_lân | phương_liệt | thanh_xuân | htxdongduong@gmailcom | hạn_nộp_hồ_sơ",
        "công_ty | nhân_viên | kinh_doanh | dịch_vụ | số_lượng | kinh_doanh | dịch_vụ | sản_phẩm | liên_quan | dịch_vụ | công_ty | thương_thảo | nhu_cầu | thiết_kế | website | kỹ_thuật | quyền_lợi | doanh_thu | năng_lực | đào_tạo | tổ_chức | sinh_nhật | chi_tiết | công_ty_tnhh_xjk | thiết_kế | website | phần_mềm | webiste | để_ứng_tuyển | vongaxjk@gmailcom",
        "tuyển_nhân_viên_kinh_doanh | giám_sát | khách_hàng | kinh_doanh | giám_sát | sự_kiện | sự_kiện | mô_tả_công_việc | tiếp_xúc | đàm_phán | thương_lượng | xúc_tiến | hợp_đồng | cung_cấp | khách_hàng | dụng_cụ | sự_kiện | âm_thanh | ánh_sáng | sân_khấu | quyền_lợi_được_hưởng | cố_định | doanh_số | sự_kiện | hấp_dẫn | công_tác_phí | điện_thoại | máy_tính | riêng_biệt | làm_việc | kết_thúc | làm_việc | chuyên_nghiệp | ổn_định | năng_động | nghề_nghiệp | làm_việc | sáng_tạo | yêu_cầu_và_quyền_lợi_khác | yêu_cầu | bằng_cấp | đặc_thù | nhiệt_tình | khả_năng | thành_thạo | văn_phòng | hình_ảnh | ưu_tiên | khai_thác | sự_kiện | liên_quan | địa_phương | điện_thoại | mtdcomvn | mtd_việt_nam",
        "công_ty | nhân_viên | hành_chính | đối_tượng | đại_học | chuyên_ngành | sinh_viên | nội_dung | công_việc | công_việc | hành_chính | thoả_thuận | trực_tiếp | môi_trường | làm_việc | vô_cùng | năng_động | sáng_tạo | thăng_tiến | địa_chỉ | công_ty | liên_hệ",
        "kinh_doanh | số_lượng | hành_chính | số_lượng | nhân_viên | kinh_doanh | xây_dựng | chăm_sóc | khách_hàng | kế_hoạch | marketing | hoàn_thành | chỉ_tiêu | tuân_thủ | văn_hóa | công_ty | nhân_viên | hành_chính | kinh_doanh | phòng_ban | hoàn_thành | công_việc | kế_hoạch | xây_dựng | văn_hóa | ứng_viên | có_tuổi | yêu_thích | công_việc | kinh_doanh | ưu_tiên | kinh_nghiệm | văn_hóa | đối_với | nhân_viên | partime | cao_đẳng | trở_lên | đối_với | nhân_viên | phương_tiện | intrernet | văn_phòng | thành_thạo | chuyên_nghiệp | năng_động | kinh_nghiệm | bài_bản | training | kỹ_năng | sản_phẩm | thành_công | tiếp_cận | phúc_lợi | viết_tay | bằng_cấp | chuyên_môn | nghiệp_vụ | lý_lịch | chứng_minh_thư | nhân_dân | gia_đình | công_ty | trúng_tuyển | chi_nhánh",
        
        /*==Query=========================================================*/
        "v_english | công_việc | tìm_kiếm | khách_hàng | sinh_viên | thu_thập | thông_tin | khách_hàng | khách_hàng | khách_hàng | bộ_phận | ghi_danh | yêu_cầu | nhiệt_tình | học_hỏi | quyền_lợi | thời_gian | làm_việc | linh_động | đào_tạo | đào_tạo | đào_tạo | lãnh_đạo | kinh_doanh | hoa_hồng | trao_đổi | phỏng_vấn | bản_sao | hộ_khẩu | bản_sao | liên_quan | tóm_tắt | giới_thiệu | liên_hệ | địa_chỉ | nguyễn_hữu_thọ | điện_thoại",
        "tuyển_nv_lắp_ráp | lao_động_phổ_thông | trung_tâm_nội_thất_phố_xinh | nhân_viên | lắp_ráp | địa_điểm | làm_việc | lê_văn_lương_kéo | vận_chuyển | lắp_đặt | nội_thất | công_việc | làm_việc | liên_hệ | thuynsphoxinh@gmailcom",
        "tuyển_dụng_nhân_sự | vị_trí_trợ_lý_tuyển_dụng | yêu_cầu | bằng_cấp | tốt_nghiệp | cao_đẳng | trở_lên | số_lượng | thời_gian | yêu_cầu | mô_tả_công_việc | quản_lý | hướng_dẫn | ứng_viên | thủ_tục | tuyển_dụng | ứng_viên | kèm_cặp | ban_đầu | nhân_viên | quyền_lợi_được_hưởng | năng_động | chuyên_nghiệp | hấp_dẫn | thăng_tiến | công_bằng | nước_ngoài | hoàn_thành | đào_tạo | nghiệp_vụ | thường_xuyên | yêu_cầu_khác | nhiệt_tình | kinh_nghiệm | kế_toán | tài_chính | vị_trí_nhân_viên_kinh_doanh | mô_tả_công_việc | khách_hàng | công_việc | quyền_lợi_đc_hưởng | chuyên_nghiệp | năng_động | đào_tạo | chuyên_môn | nhân_viên | chuyên_nghiệp | khả_năng | thăng_tiến | đào_tạo | thường_xuyên | phát_triển | bản_thân | xứng_đáng | yêu_cầu_công_việc | kinh_nghiệm | địa_chỉ_chi_tiết_nơi_làm_việc | thông_tin_liên_hệ",
        "công_ty | nhân_viên | hành_chính | đối_tượng | đại_học | chuyên_ngành | sinh_viên | nội_dung | công_việc | công_việc | hành_chính | thoả_thuận | trực_tiếp | môi_trường | làm_việc | vô_cùng | năng_động | sáng_tạo | thăng_tiến | địa_chỉ | công_ty | liên_hệ",
        "outsourcing | pythonjavaphp | kỹ_thuật | kỹ_năng | giải_trí | thể_thao | sức_khỏe | sức_khỏe | cao_cấp",
    };    
}
